package com.cv.demo.kotapi.config.security

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityWebApplicationInitializer : AbstractSecurityWebApplicationInitializer()